services:
  # БД
  postgres:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 1s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_DB: "mydb"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    restart: always
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "http://localhost:8080/"
      DB_LOGIN: "myuser"
      DB_NAME: "mydb"
      DB_PASSWORD: "1234"
