POST http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4MTYzNzQsIklEIjoxfQ._oYQoJcZEflQTQj5C7cLswIpU5n6AdsyHvhpZei_sj0
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ5ODkxNzQsIklEIjowfQ.zLphKyBhUr62DIOcQ4OYACPoE3kvGJoECX6fDvu_mBI

{
    "login": "user1",
    "password": "pass1"    
}

###

GET http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4OTc5NzksIklEIjoxfQ.tb5FD5_2zHdGgxYWktgxitFz7PWcWwrgF1K2w0lC_vs
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDUwNzA3NzksIklEIjowfQ.O_DgPe3BVh9sZ6ZRKQzjfo8YWpkWTpZ563QPv1Ml37Y

###

PUT http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3MDM3NjMsIklEIjoxMn0.PCAkTdFAaTrjbQdr2c_7YDGiNOS03k6gHKnmV4IPCsQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4NzY1NjMsIklEIjowfQ.uD3JXonERjprCaNqnVZMxbBzoQ-igyB6vjmW1o3jQ-0

{
    "id" : 22,
    "login": "useasdfdcsavzfr"
}



