POST http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3MDM3NjMsIklEIjoxMn0.PCAkTdFAaTrjbQdr2c_7YDGiNOS03k6gHKnmV4IPCsQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4NzY1NjMsIklEIjowfQ.uD3JXonERjprCaNqnVZMxbBzoQ-igyB6vjmW1o3jQ-0

{
    "login": "usedcvzfr",
    "password": "pasdfwess1"    
}

###

GET http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3MDM3NjMsIklEIjoxMn0.PCAkTdFAaTrjbQdr2c_7YDGiNOS03k6gHKnmV4IPCsQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4NzY1NjMsIklEIjowfQ.uD3JXonERjprCaNqnVZMxbBzoQ-igyB6vjmW1o3jQ-0

###

PUT http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3MDM3NjMsIklEIjoxMn0.PCAkTdFAaTrjbQdr2c_7YDGiNOS03k6gHKnmV4IPCsQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4NzY1NjMsIklEIjowfQ.uD3JXonERjprCaNqnVZMxbBzoQ-igyB6vjmW1o3jQ-0

{
    "id" : 22,
    "login": "useasdfdcsavzfr"
}



