POST http://localhost:8080/register HTTP/1.1
content-type: application/json

{
    "login": "u",
    "password": "p"
}

###

POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "login": "u",
    "password": "p"
}

###
GET http://localhost:8080/user/accounts HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDYxNzkyMDcsIklEIjoxNX0.IKCS2Tm02-fIJp8d_aanZTUtfWxUhrvuSYG5VaDJ0GQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDYzNTIwMDcsIklEIjowfQ.HyuDPJ0McSFc7Jo33dyhDrmaUJ_ExEXFU_ZnsmVfmys

{
    "login": "user1sfas2",
    "password": "pass1"
}
