PUT http://localhost:8080/user/metadata HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ3MDM3NjMsIklEIjoxMn0.PCAkTdFAaTrjbQdr2c_7YDGiNOS03k6gHKnmV4IPCsQ
Refresh-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDQ4NzY1NjMsIklEIjowfQ.uD3JXonERjprCaNqnVZMxbBzoQ-igyB6vjmW1o3jQ-0

{
    "id": 6,
}



